project:
  type: website

website:
  title: "Teevial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - demographics.qmd
      - waterhome.qmd
      - waternature.qmd
      - interests.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



